### PR TITLE
chore: run `apt-get update` before running other commands

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Run `sudo apt-get update` before running other commands on the Gitpod Dockerfile.

### CODE REVIEW

**Comment by dlesnoff** [comment]
Isn't an `apt-get upgrade` necessary after an update?

**Comment by Panquesito7** [comment]
> Isn't an `apt-get upgrade` necessary after an update?

Sometimes, not all of the packages are updated, even on the first start, AFAIK.

**Review by dlesnoff — APPROVED** [review]
Looks good to me.

**Comment by vil02** [comment]
@Panquesito7 I know that this was already merged, but I would like to know why do you think this change is needed? Is it recommended to run `sudo apt-get update` before executing the `https://nim-lang.org/choosenim/init.sh` script?

**Comment by dlesnoff** [comment]
`curl` might not be up to date.

**Comment by vil02** [comment]
`sudo apt-get update` only updates the _package index_. In this case `sudo apt-get upgrade` is needed.

A side remark: in my opinion having a not updated `curl' is a smaller problem than using `sudo` in a docker file.

**Comment by dlesnoff** [comment]
I will check Docker's security recommendations tomorrow.

**Comment by vil02** [comment]
After thinking about it, I have a strong opinion: this change should be reverted. The reasons are as follows:
- `apt-get update` updates the _index_ (and this is not needed in this case),
- adding `upgrade` in order to update installed packages like `curl` does not make sense: this should be done _inside_ the image `gitpod/workspace-base`.

@dlesnoff @Panquesito7 if you agree with me, I will make a suitable PR.

**Comment by dlesnoff** [comment]
I revert it, and I wait for a better suggestion.

**Pull request merged**
