### PR TITLE
Add arc length (circle)

### PR DESCRIPTION
**Pull request by dlesnoff**
Compute arc length on a circle for both degrees and radians input. Generic curves would require integration algorithms.
Based on [Python's implementation](https://the-algorithms.com/algorithm/arc-length)

### CODE REVIEW

**Review by SatinWuker — APPROVED** [review]

**Comment by dlesnoff** [comment]
Strange. Why @SatinWuker 's approving review did not unlock merging?
@Panquesito7 Is it a GitHub bug?

**Comment by SatinWuker** [comment]
I think you need one more approval to unlock merging lol

**Comment by Panquesito7** [comment]
> Strange. Why @SatinWuker 's approving review did not unlock merging? @Panquesito7 Is it a GitHub bug?

That's because they do not have write+ access in the repository.

**Review by Panquesito7 — APPROVED** [review]
Approving to allow the merge. Thanks. 👍

**Pull request merged**
